[package]
name = "pyrlu"
version = "0.2.0"
edition = "2021"

[lib]
name = "pyrlu"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.17", features = ["extension-module"] }
numpy = "0.17"

amd = "0.2.2"
rlu = { version = "=0.7.0", features = ["rayon"] }
